### ISSUE TITLE
Extension usage and compatibility with Xilinx

### ISSUE THREAD

**Issue by dookei** [intel/vscode-tcf-debug#1]
Hi @iebold,
this is great news. I would like to develop under VSCode for the Xilinx MPSoC devices without using the tools from xilinx(Requires 40Gb of space and dont perform good under Linux.).
Could you please provide the link to the extension (.VSIX file)? I dont find it under the repo.

**Comment by iebold** [comment]
We will provide a .VSIX file soon. In the mean time you can build it yourself by running `npm run package` in the `vscode-tcf-debug` folder.

Can't comment on specific debugger support. If they provide a TCF connection "it should work". Of course, there may be specific issues with a given debugger (version).

Note that the project itself is quite early and may not have something specific implemented yet.

Looking forwards to any TCF-level / debugging issues you may encounter using the code.

**Comment by dookei** [comment]
Thank you for your reply. I encountered some issues on building
Not sure if related to this package or npm

```
vscode-tcf-debug $ npm run package

> vscode-tcf-debug@0.2.2 package
> npx vsce package -o vscode-tcf-debug.vsix --baseImagesUrl https://github.com/intel-innersource/applications.vpu.tools.tcf-vscode-debug/raw/HEAD/vscode-tcf-debug/

/home/ubuntu/.npm/_npx/28f98e99224dac41/node_modules/vsce/out/package.js:136
    return (translations ?? [])
                          ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/ubuntu/.npm/_npx/28f98e99224dac41/node_modules/vsce/out/main.js:27:19)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
```

**Comment by iebold** [comment]
Your `npm` is probably very old.

**Comment by dookei** [comment]
> Your `npm` is probably very old.

What version do you recommend? 
```
 vscode-tcf-debug $ npm -v
8.5.1
 vscode-tcf-debug $ node -v
v12.22.9
```

**Comment by iebold** [comment]
Please try with node v18.

**Comment by dookei** [comment]
Thanks it worked.

`curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -`

I will give it a go in the next days.

**Comment by dookei** [comment]
I started already a quick test...Some work to be done in order to get this working with xilinx 

The extension is enabled.
Here ins my Debug Console output

`09:40:45 TCF debug session initialized
09:40:45 Launch request [object Object]
09:40:45 Connected!
09:40:45 Unknown service event: Xicom_v1.00.numChannelsUpdated
Set breakpoints for /home/ubuntu/Vitis_Workspace/Hello/src/helloworld.c09:40:45 Eroneous breakpoint emi-0 hit {"Instances":[{"LocationContext":"JTAG-jsn-JTAG-ONB4-251633002923A-5ba00477-0R0","Error":"Unresolved source line information"},{"LocationContext":"JTAG-jsn-JTAG-ONB4-251633002923A-5ba00477-0R1","Error":"Unresolved source line information"},{"LocationContext":"JTAG-jsn-JTAG-ONB4-251633002923A-5ba00477-0A0","Error":"Unresolved source line information"},{"LocationContext":"JTAG-jsn-JTAG-ONB4-251633002923A-5ba00477-0A0.0","Error":"Unresolved source line information"},{"LocationContext":"JTAG-jsn-JTAG-ONB4-251633002923A-5ba00477-0A0.1","Error":"Unresolved source line information"},{"LocationContext":"JTAG-jsn-JTAG-ONB4-251633002923A-5ba00477-0A0.2","Error":"Unresolved source line information"},{"LocationContext":"JTAG-jsn-JTAG-ONB4-251633002923A-5ba00477-0A0.3","Error":"Unresolved source line information"},{"LocationContext":"JTAG-jsn-JTAG-ONB4-251633002923A-5ba00477-0A1","Error":"Unresolved source line information"},{"LocationContext":"JTAG-jsn-JTAG-ONB4-251633002923A-5ba00477-0A1.0","Error":"Unresolved source line information"},{"LocationContext":"JTAG-jsn-JTAG-ONB4-251633002923A-5ba00477-0A1.1","Error":"Unresolved source line information"},{"LocationContext":"JTAG-jsn-JTAG-ONB4-251633002923A-5ba00477-0A1.2","Error":"Unresolved source line information"},{"LocationContext":"JTAG-jsn-JTAG-ONB4-251633002923A-5ba00477-0A1.3","Error":"Unresolved source line information"}]}`

Any thoughts where I should start looking for ? Many Many thanks

**Comment by iebold** [comment]
> Unknown service event: Xicom_v1.00.numChannelsUpdated

This is normal. It's a non-standard event.

> "Error":"Unresolved source line information"

Many of these may also be fine. A breakpoint is set on all cores/"contexts", usually, but not all will execute the binary and thus there's no source line information.

The extension may actually work after all these messages. Does it not?

Make sure the paths match the debug symbols. Note how VSCode sends the full path (`/home/ubuntu/...`).

**Comment by dookei** [comment]
No it does not work. 
I send you in attachment the project example. Is nothing fancy just a simple COM Hello World.

[Hello.zip](https://github.com/intel/vscode-tcf-debug/files/12780879/Hello.zip)

**Comment by iebold** [comment]
I can't / won't execute foreign binaries on systems I don't use :-)

I am mostly commenting here from the perspective of a TCF / VSCode debug client. 

If you read the manual https://github.com/intel/vscode-tcf-debug/blob/main/vscode-tcf-debug/docs/manual.md you'll note the `debugTCFMessages` flag. This may provide more gory details.

**Comment by dookei** [comment]
> I can't / won't execute foreign binaries on systems I don't use :-)

I understand. Either way I had wrong port and IP set.
`
12:29:19 TCF debug session initialized
12:29:19 Launch request [object Object]
12:29:19 Connected!
Set breakpoints for /home/ubuntu/Vitis_Workspace/hello/src/helloworld.c12:29:19 Eroneous breakpoint file:/home/ubuntu/Vitis_Workspace/hello/src/helloworld.c:559 hit {}
`
![image](https://github.com/intel/vscode-tcf-debug/assets/24986481/8162cc41-3089-46f1-8d2d-e476226cf220)

**Q1:** Should hte application be loaded and set to running in a parallel instance? 
**Q2:** How do I match the breakpoint files ?

**Comment by iebold** [comment]
> Q1: Should hte application be loaded and set to running in a parallel instance?

Yes, the extension does not launch anything. It only connects to the running debugger TCF agent.

> Q2: How do I match the breakpoint files ?

Generally you don't have to do anything, *if* the full paths are saved in the debug symbols. Breakpoints won't work, obviously, if the debugger can't find a corresponding address for a file line.

Note the extension can connect to a suspended debugger too! Ie. you don't have to start from scratch.

**Comment by dookei** [comment]
I guess I will not use this for the moment ....It requires "some" tweaking and I am tight on schedule .
It "works"  when I run a Debug instance from Vitis(Xilinx IDE) but then it kinda defies the all objective of getting rid of the Xilinx ide.
There are some things that are missing: registers values panel, TCF debug terminal,   etc 
But I love the idea of porting this to VSCode.
I will give it another shot when I have a little more time.  
Many thanks and keep up the good work.

**Comment by iebold** [comment]
Thanks for looking into it. We are currently adding disassembly support.

**Comment by iebold** [comment]
> It "works" when I run a Debug instance from Vitis(Xilinx IDE) but then it kinda defies the all objective of getting rid of the Xilinx ide.

Note that it doesn't need a companion IDE, it needs the TCF debugger. I assume whatever IDE you are using does have a command line debugger. In theory you only need that.

> There are some things that are missing: registers values panel, TCF debug terminal, etc

These are also on our roadmap.

**Comment by dookei** [comment]
Yes I realize that. Just did that for testing to see if it was working. 
I first launched the IDE(Eclipse/Vitis) that uses xsct(xilinx TCF debugger) and then launched  the debug extension in VSCode.
This kinda works. The execution line is offset-ed  compared to the Eclipse IDE and can perform the standard debug steps. 

I would love to move away from the xilinx IDE. But at the moment this is offering me better/easier debug experience.
There three main basic functionalities that need to be done for me in order to completly move to this extension and develop and 
debug entirely under Vscode: 

1. Load the .elf  application over xsct rootfs (for example /run/media/mmcblk0p1/) 
2. start the application and make it stop at breakpoint(main for example)
3.  TCF debug process terminal (nice to have) / Pseudo-terminal for process standard I/O

If this 3 functionalities would be possibles I believe a lot of people would move from the heavy and closed source Vitis IDE to this .
Sure this is more to do with TCF usage than with this extension.

**Comment by iebold** [comment]
> 1. Load the .elf application over xsct rootfs (for example /run/media/mmcblk0p1/)
> 2. start the application [...]

This is something your (TCF-aware) debugger should do. In theory you can open a terminal inside VSCode and launch your script / debugger from there which does this loading / starting.

> 2. [...] and make it stop at breakpoint(main for example)

Assuming the debugger accepts the TCF breakpoints this should work today.

> 3. TCF debug process terminal (nice to have) / Pseudo-terminal for process standard I/O

I'm not entirely sure what you mean here. If you open the normal Terminal inside VSCode you can see your debugger and whatever the debugger outputs.

If you mean the TCF Terminals Service then, yes, that's not implemented yet.

**Comment by dookei** [comment]
I am still kinda stuck in point 1. and 2. 
Xilinx doesnt provide any example or documentation on this process. I would like to upload the .elf over tcf to the rfs/linux_fs
Do you know how to do this by any chance ? ;-)

The 3. yes I mean TCF terminals service

**Comment by pelrun** [comment]
I've got a little headway into this. The things you *absolutely* need to be running from the Xilinx SDK to get a functioning debug environment are `hw_server` and `symbol_server`. With symbol_server running, creating a MemoryMap entry with the source .elf will fully enable the various services that provide source code and symbol information to the debugger frontend. 

Doing a 'dow' in XSCT will automatically populate the memorymap, but you want to have launched symbol_server manually as doing it from XSCT (via the -symbols option to connect) will terminate the server after a few seconds of inactivity and you want it to be hanging around. It would be nice to have a way to set the memorymap from this extension at some point.

I've managed to get the extension to give me a stack trace on break a couple of times, but it's not robust yet - certain cases seem to have it get a valid response to a StackTrace.getChildren call, but then throw a timeout error anyway.

**Comment by pelrun** [comment]
It's also good to know that Xilinx's xsdb is entirely implemented in TCL, so it's possible to read `SDK/scripts/xsdb/xsdb.tcl` amongst other files in the same location to get some insight into how they actually do things.

**Comment by iebold** [comment]
> I've managed to get the extension to give me a stack trace on break a couple of times, but it's not robust yet - certain cases seem to have it get a valid response to a StackTrace.getChildren call, but then throw a timeout error anyway.

Assuming you enabled `debugTCFMessages` I would be curious to see the TCF response and error you received. It's possible there a bug or a schema mismatch (TCF messages are supposed to follow a specific schema, but debuggers often take some liberties).

Also note that sometimes things may actually run very slow. You then need to bump `timeout` config.

**Comment by iebold** [comment]
I'm thinking of closing this issue since it's too broad.

As far as I can tell it touched:

* needing a VSIX build release (which we are tracking internally).
* needing better documentation about how to build (specifically, npm / node versions expected). This seems reasonable.
* Xilinx compatibility which we are not specifically targeting but should work if TCF compliant
* mentioned registers view which we will add in the future.
* and TCF Terminals Service which is also on the roadmap.

Feel free to open new issue about specific concerns.

**Comment by iebold** [comment]
We now have releases too https://github.com/intel/vscode-tcf-debug/releases/tag/v0.2.6

(Disassembly was also added a while back.)

**Comment by wwbenayed** [comment]
I added the support of empty breakpoint set to TRACE32.
Now I can see that it doesn't find the source file, but I can see the path given in the log:
![image](https://github.com/intel/vscode-tcf-debug/assets/19547530/479ca8f2-55d7-41d6-9e17-4927b38daa0c)
![image](https://github.com/intel/vscode-tcf-debug/assets/19547530/1ca01f58-f571-44ed-9199-0456b1917e00)

Also, neither continue, break or step is working (nothing printed in the log when I press the buttons in VSCode).

**Comment by iebold** [comment]
@wwbenayed  I've created https://github.com/intel/vscode-tcf-debug/issues/4 and https://github.com/intel/vscode-tcf-debug/issues/5 for your problems.

Please create new issues for new situations.
