### ISSUE TITLE
How to debug program  and add symbol?

### ISSUE THREAD

**Issue by fbs2016** [intel/vscode-tcf-debug#7]
I can connect to tcf agent on target with port 1534. And how to configure the program and file symbol to debug it?
From the configurations of launch.json, I can't find like "program" attributes to configure it. Thanks

**Comment by ovidiuostoia** [comment]
Hi,

Your tcf agent should communicate with your debugger to debug the program.

**Comment by kdurant** [comment]
@fbs2016 Are you trying to debug a C program on Petalinux? Have you configured it yet?
